services:
  - type: web
    name: php-inventory-app
    env: php
    plan: free
    buildCommand: ''
    startCommand: ''
    envVars:
      - key: DB_HOST
        value: your-postgresql-service.internal
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: render_user  # Change to your PostgreSQL user
      - key: DB_PASS
        value: your_db_password  # Change to your PostgreSQL password
      - key: DB_NAME
        value: render_db  # Change to your PostgreSQL database name

  - type: psql
    name: php-inventory-database
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
