services:
  - type: web
    name: php-inventory-app
    env: php
    plan: free
    buildCommand: ''
    startCommand: ''
    envVars:
      - key: DB_HOST
        value: ep-polished-glade-a4ncvcqh-pooler.us-east-1.aws.neon.tech  # Host from the connection string
      - key: DB_PORT
        value: 5432  # Standard PostgreSQL port
      - key: DB_USER
        value: default  # Username from the connection string
      - key: DB_PASS
        value: AUlTy6q0CmpD  # Password from the connection string
      - key: DB_NAME
        value: verceldb  # Database name from the connection string
      - key: DB_URL
        value: "postgres://default:AUlTy6q0CmpD@ep-polished-glade-a4ncvcqh-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"  # Full connection string

  - type: psql
    name: php-inventory-database
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
